import { Employee, Activity, Notification, DashboardStats, QuickAction } from "../types/employeeDashboard";

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    phone: "123-456-7890",
    position: "Software Engineer",
    department: "Engineering",
    hireDate: "2022-01-15",
    status: "active",
    salary: 90000,
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "90210",
    },
    skills: ["React", "TypeScript", "Node.js"],
    performanceScore: 85,
    lastReviewDate: "2023-07-01",
  },
  {
    id: "emp-002",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    phone: "098-765-4321",
    position: "Product Manager",
    department: "Product",
    hireDate: "2021-03-20",
    status: "active",
    salary: 110000,
    address: {
      street: "456 Oak Ave",
      city: "Anytown",
      state: "CA",
      zip: "90210",
    },
    managerId: "emp-001",
    skills: ["Agile", "Roadmapping", "UX/UI"],
    performanceScore: 92,
    lastReviewDate: "2023-08-10",
  },
  {
    id: "emp-003",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@example.com",
    phone: "111-222-3333",
    position: "HR Specialist",
    department: "Human Resources",
    hireDate: "2023-05-01",
    status: "on_leave",
    salary: 70000,
    address: {
      street: "789 Pine Ln",
      city: "Anytown",
      state: "CA",
      zip: "90210",
    },
    skills: ["Recruitment", "Onboarding", "Employee Relations"],
    performanceScore: 78,
    lastReviewDate: "2023-06-15",
  },
  {
    id: "emp-004",
    firstName: "Diana",
    lastName: "Prince",
    email: "diana.prince@example.com",
    phone: "444-555-6666",
    position: "Marketing Coordinator",
    department: "Marketing",
    hireDate: "2022-11-01",
    status: "active",
    salary: 65000,
    address: {
      street: "101 Cedar Rd",
      city: "Anytown",
      state: "CA",
      zip: "90210",
    },
    skills: ["Social Media", "Content Creation", "SEO"],
    performanceScore: 88,
    lastReviewDate: "2023-09-01",
  },
  {
    id: "emp-005",
    firstName: "Eve",
    lastName: "Adams",
    email: "eve.adams@example.com",
    phone: "777-888-9999",
    position: "Software Engineer",
    department: "Engineering",
    hireDate: "2023-02-10",
    status: "inactive",
    salary: 95000,
    address: {
      street: "202 Birch Blvd",
      city: "Anytown",
      state: "CA",
      zip: "90210",
    },
    skills: ["Python", "AWS", "Machine Learning"],
    performanceScore: 90,
    lastReviewDate: "2023-07-20",
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act-001",
    employeeId: "emp-001",
    type: "task_completed",
    description: "Completed sprint task #123",
    timestamp: "2025-09-27T10:00:00Z",
  },
  {
    id: "act-002",
    employeeId: "emp-002",
    type: "leave_request",
    description: "Submitted vacation request for Oct 2025",
    timestamp: "2025-09-26T14:30:00Z",
  },
  {
    id: "act-003",
    employeeId: "emp-003",
    type: "update_profile",
    description: "Updated contact information",
    timestamp: "2025-09-25T09:15:00Z",
  },
  {
    id: "act-004",
    employeeId: "emp-001",
    type: "login",
    description: "Logged in to the system",
    timestamp: "2025-09-27T08:00:00Z",
  },
  {
    id: "act-005",
    employeeId: "emp-004",
    type: "performance_review",
    description: "Received Q3 performance review",
    timestamp: "2025-09-24T16:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "not-001",
    employeeId: "emp-001",
    message: "Your Q3 performance review is due next week.",
    type: "warning",
    read: false,
    timestamp: "2025-09-27T09:00:00Z",
  },
  {
    id: "not-002",
    employeeId: "emp-002",
    message: "New company policy on remote work has been published.",
    type: "info",
    read: true,
    timestamp: "2025-09-26T11:00:00Z",
  },
  {
    id: "not-003",
    employeeId: "emp-003",
    message: "Your leave request has been approved.",
    type: "success",
    read: false,
    timestamp: "2025-09-25T15:00:00Z",
  },
  {
    id: "not-004",
    employeeId: "emp-004",
    message: "Upcoming team meeting on Friday at 10 AM.",
    type: "info",
    read: false,
    timestamp: "2025-09-27T08:30:00Z",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEmployees: mockEmployees.length,
  activeEmployees: mockEmployees.filter((emp) => emp.status === "active").length,
  onLeaveEmployees: mockEmployees.filter((emp) => emp.status === "on_leave").length,
  newHiresLastMonth: 2, // Example value
  averagePerformanceScore: Math.round(
    mockEmployees.reduce((sum, emp) => sum + emp.performanceScore, 0) / mockEmployees.length
  ),
};

export const mockQuickActions: QuickAction[] = [
  {
    id: "qa-001",
    label: "Add New Employee",
    icon: "plus",
    action: "add_employee",
  },
  {
    id: "qa-002",
    label: "View Reports",
    icon: "chart",
    action: "view_reports",
  },
  {
    id: "qa-003",
    label: "Manage Leave",
    icon: "calendar",
    action: "manage_leave",
  },
  {
    id: "qa-004",
    label: "Performance Reviews",
    icon: "star",
    action: "performance_reviews",
  },
];
