import { Employee } from "../types/employee";

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    phone: "+1-555-123-4567",
    address: "123 Main St, Anytown, USA",
    dateOfBirth: "1988-03-15",
    hireDate: "2015-06-01",
    department: "Engineering",
    position: "Software Engineer",
    salary: 95000,
    status: "active",
    photoUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    skills: [
      { id: "skill-001", name: "React", level: "expert", yearsOfExperience: 7 },
      { id: "skill-002", name: "TypeScript", level: "advanced", yearsOfExperience: 5 },
      { id: "skill-003", name: "Node.js", level: "intermediate", yearsOfExperience: 4 },
    ],
    certifications: [
      { id: "cert-001", name: "AWS Certified Developer", issuingOrganization: "Amazon Web Services", issueDate: "2019-11-01", expirationDate: "2022-11-01", credentialId: "AWS-DEV-12345" },
    ],
  },
  {
    id: "emp-002",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    phone: "+1-555-987-6543",
    address: "456 Oak Ave, Anytown, USA",
    dateOfBirth: "1992-07-22",
    hireDate: "2018-09-15",
    department: "Marketing",
    position: "Marketing Specialist",
    salary: 70000,
    status: "active",
    photoUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    skills: [
      { id: "skill-004", name: "SEO", level: "advanced", yearsOfExperience: 6 },
      { id: "skill-005", name: "Content Marketing", level: "expert", yearsOfExperience: 8 },
    ],
    certifications: [
      { id: "cert-002", name: "Google Ads Certified", issuingOrganization: "Google", issueDate: "2020-03-10", expirationDate: null, credentialId: "GA-CERT-67890" },
    ],
  },
  {
    id: "emp-003",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@example.com",
    phone: "+1-555-111-2222",
    address: "789 Pine Ln, Anytown, USA",
    dateOfBirth: "1995-01-01",
    hireDate: "2020-01-20",
    department: "Human Resources",
    position: "HR Generalist",
    salary: 60000,
    status: "on_leave",
    photoUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    skills: [
      { id: "skill-006", name: "Recruitment", level: "intermediate", yearsOfExperience: 3 },
      { id: "skill-007", name: "Employee Relations", level: "advanced", yearsOfExperience: 4 },
    ],
    certifications: [],
  },
  {
    id: "emp-004",
    firstName: "Diana",
    lastName: "Prince",
    email: "diana.prince@example.com",
    phone: "+1-555-333-4444",
    address: "101 Justice Way, Anytown, USA",
    dateOfBirth: "1980-06-20",
    hireDate: "2010-02-01",
    department: "Legal",
    position: "Legal Counsel",
    salary: 120000,
    status: "active",
    photoUrl: "https://randomuser.me/api/portraits/women/4.jpg",
    skills: [
      { id: "skill-008", name: "Contract Law", level: "expert", yearsOfExperience: 10 },
      { id: "skill-009", name: "Intellectual Property", level: "advanced", yearsOfExperience: 8 },
    ],
    certifications: [
      { id: "cert-003", name: "Juris Doctor", issuingOrganization: "Harvard Law School", issueDate: "2005-05-25", expirationDate: null, credentialId: "JD-HARV-54321" },
    ],
  },
  {
    id: "emp-005",
    firstName: "Eve",
    lastName: "Adams",
    email: "eve.adams@example.com",
    phone: "+1-555-555-6666",
    address: "202 Garden Rd, Anytown, USA",
    dateOfBirth: "1990-11-11",
    hireDate: "2017-04-01",
    department: "Finance",
    position: "Financial Analyst",
    salary: 80000,
    status: "inactive",
    photoUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    skills: [
      { id: "skill-010", name: "Financial Modeling", level: "advanced", yearsOfExperience: 6 },
      { id: "skill-011", name: "Data Analysis", level: "intermediate", yearsOfExperience: 5 },
    ],
    certifications: [
      { id: "cert-004", name: "CFA Level II", issuingOrganization: "CFA Institute", issueDate: "2021-08-01", expirationDate: null, credentialId: "CFA-INST-98765" },
    ],
  },
];
