export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    firstName: 'Alice',
    lastName: 'Smith',
    fullName: 'Alice Smith',
    email: 'alice.smith@example.com',
    phone: '+1-555-1001',
    title: 'CEO',
    department: 'Executive',
    managerId: undefined,
    hireDate: '2010-01-15',
    photoUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
    address: { street: '123 Executive Blvd', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Leadership', 'Strategy', 'Public Speaking'],
    bio: 'Visionary leader with over 20 years of experience in technology and management.',
    subordinates: ['emp-002', 'emp-003', 'emp-004'],
  },
  {
    id: 'emp-002',
    firstName: 'Bob',
    lastName: 'Johnson',
    fullName: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '+1-555-1002',
    title: 'CTO',
    department: 'Technology',
    managerId: 'emp-001',
    hireDate: '2012-03-01',
    photoUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Software Architecture', 'Cloud Computing', 'DevOps'],
    bio: 'Leads the technology division, focusing on innovation and scalable solutions.',
    subordinates: ['emp-005', 'emp-006'],
  },
  {
    id: 'emp-003',
    firstName: 'Carol',
    lastName: 'Williams',
    fullName: 'Carol Williams',
    email: 'carol.williams@example.com',
    phone: '+1-555-1003',
    title: 'CFO',
    department: 'Finance',
    managerId: 'emp-001',
    hireDate: '2011-06-20',
    photoUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
    address: { street: '789 Money St', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Financial Planning', 'Accounting', 'Risk Management'],
    bio: 'Manages all financial operations and strategic financial planning.',
    subordinates: ['emp-007'],
  },
  {
    id: 'emp-004',
    firstName: 'David',
    lastName: 'Brown',
    fullName: 'David Brown',
    email: 'david.brown@example.com',
    phone: '+1-555-1004',
    title: 'Head of HR',
    department: 'Human Resources',
    managerId: 'emp-001',
    hireDate: '2013-09-10',
    photoUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
    address: { street: '101 People Ave', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Recruitment', 'Employee Relations', 'Talent Development'],
    bio: 'Oversees all human resources functions, fostering a positive work environment.',
    subordinates: ['emp-008'],
  },
  {
    id: 'emp-005',
    firstName: 'Eve',
    lastName: 'Davis',
    fullName: 'Eve Davis',
    email: 'eve.davis@example.com',
    phone: '+1-555-1005',
    title: 'Lead Software Engineer',
    department: 'Technology',
    managerId: 'emp-002',
    hireDate: '2015-02-01',
    photoUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['React', 'Node.js', 'TypeScript', 'Database Design'],
    bio: 'Senior engineer specializing in frontend development and system architecture.',
    subordinates: ['emp-009', 'emp-010'],
  },
  {
    id: 'emp-006',
    firstName: 'Frank',
    lastName: 'Miller',
    fullName: 'Frank Miller',
    email: 'frank.miller@example.com',
    phone: '+1-555-1006',
    title: 'DevOps Engineer',
    department: 'Technology',
    managerId: 'emp-002',
    hireDate: '2016-07-18',
    photoUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['AWS', 'Kubernetes', 'CI/CD', 'Scripting'],
    bio: 'Ensures smooth deployment and operation of all software systems.',
    subordinates: [],
  },
  {
    id: 'emp-007',
    firstName: 'Grace',
    lastName: 'Wilson',
    fullName: 'Grace Wilson',
    email: 'grace.wilson@example.com',
    phone: '+1-555-1007',
    title: 'Senior Accountant',
    department: 'Finance',
    managerId: 'emp-003',
    hireDate: '2014-11-05',
    photoUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
    address: { street: '789 Money St', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Auditing', 'Tax Preparation', 'Financial Reporting'],
    bio: 'Responsible for managing company accounts and financial records.',
    subordinates: [],
  },
  {
    id: 'emp-008',
    firstName: 'Henry',
    lastName: 'Moore',
    fullName: 'Henry Moore',
    email: 'henry.moore@example.com',
    phone: '+1-555-1008',
    title: 'HR Specialist',
    department: 'Human Resources',
    managerId: 'emp-004',
    hireDate: '2017-04-22',
    photoUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
    address: { street: '101 People Ave', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Onboarding', 'Payroll', 'Benefits Administration'],
    bio: 'Supports HR operations and employee welfare programs.',
    subordinates: [],
  },
  {
    id: 'emp-009',
    firstName: 'Ivy',
    lastName: 'Taylor',
    fullName: 'Ivy Taylor',
    email: 'ivy.taylor@example.com',
    phone: '+1-555-1009',
    title: 'Software Engineer',
    department: 'Technology',
    managerId: 'emp-005',
    hireDate: '2019-08-12',
    photoUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['JavaScript', 'Python', 'API Development'],
    bio: 'Develops and maintains backend services and APIs.',
    subordinates: [],
  },
  {
    id: 'emp-010',
    firstName: 'Jack',
    lastName: 'Anderson',
    fullName: 'Jack Anderson',
    email: 'jack.anderson@example.com',
    phone: '+1-555-1010',
    title: 'Frontend Developer',
    department: 'Technology',
    managerId: 'emp-005',
    hireDate: '2020-01-25',
    photoUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['React', 'HTML/CSS', 'UI/UX Design'],
    bio: 'Focuses on creating intuitive and responsive user interfaces.',
    subordinates: [],
  },
  {
    id: 'emp-011',
    firstName: 'Karen',
    lastName: 'Thomas',
    fullName: 'Karen Thomas',
    email: 'karen.thomas@example.com',
    phone: '+1-555-1011',
    title: 'Marketing Manager',
    department: 'Marketing',
    managerId: 'emp-001',
    hireDate: '2018-03-15',
    photoUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
    address: { street: '202 Creative Way', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Digital Marketing', 'Content Strategy', 'SEO'],
    bio: 'Leads marketing initiatives to promote brand awareness and growth.',
    subordinates: ['emp-012'],
  },
  {
    id: 'emp-012',
    firstName: 'Liam',
    lastName: 'Jackson',
    fullName: 'Liam Jackson',
    email: 'liam.jackson@example.com',
    phone: '+1-555-1012',
    title: 'Marketing Specialist',
    department: 'Marketing',
    managerId: 'emp-011',
    hireDate: '2021-06-01',
    photoUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
    address: { street: '202 Creative Way', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Social Media', 'Email Campaigns', 'Analytics'],
    bio: 'Executes marketing campaigns and analyzes performance data.',
    subordinates: [],
  },
  {
    id: 'emp-013',
    firstName: 'Mia',
    lastName: 'White',
    fullName: 'Mia White',
    email: 'mia.white@example.com',
    phone: '+1-555-1013',
    title: 'Product Manager',
    department: 'Product',
    managerId: 'emp-002',
    hireDate: '2017-09-01',
    photoUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
    address: { street: '303 Innovation Dr', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Product Strategy', 'Roadmapping', 'Agile Methodologies'],
    bio: 'Defines product vision and oversees the product development lifecycle.',
    subordinates: [],
  },
  {
    id: 'emp-014',
    firstName: 'Noah',
    lastName: 'Harris',
    fullName: 'Noah Harris',
    email: 'noah.harris@example.com',
    phone: '+1-555-1014',
    title: 'Data Scientist',
    department: 'Technology',
    managerId: 'emp-005',
    hireDate: '2018-11-11',
    photoUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['Machine Learning', 'Statistical Analysis', 'Python'],
    bio: 'Analyzes complex data to derive insights and build predictive models.',
    subordinates: [],
  },
  {
    id: 'emp-015',
    firstName: 'Olivia',
    lastName: 'Martin',
    fullName: 'Olivia Martin',
    email: 'olivia.martin@example.com',
    phone: '+1-555-1015',
    title: 'UX Designer',
    department: 'Technology',
    managerId: 'emp-005',
    hireDate: '2019-05-20',
    photoUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
    address: { street: '456 Tech Lane', city: 'Metropolis', state: 'NY', zip: '10001' },
    skills: ['User Research', 'Wireframing', 'Prototyping', 'Figma'],
    bio: 'Designs intuitive and user-friendly interfaces for our products.',
    subordinates: [],
  },
];
