import { Goal, Milestone, ProgressUpdate, GoalStatus, GoalPriority } from './goalTracking.d';

const generateId = (): string => Math.random().toString(36).substr(2, 9);

const generateMilestone = (goalId: string, name: string, description: string, dueDate: string, status: GoalStatus, progress: number): Milestone => ({
  id: generateId(),
  goalId,
  name,
  description,
  dueDate,
  status,
  progress,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

const generateProgressUpdate = (goalId: string, notes: string, progressPercentage: number, milestoneId?: string): ProgressUpdate => ({
  id: generateId(),
  goalId,
  milestoneId,
  date: new Date().toISOString().split('T')[0],
  notes,
  progressPercentage,
  attachments: [],
  createdAt: new Date().toISOString(),
});

export const mockGoals: Goal[] = [
  {
    id: 'goal-1',
    employeeId: 'emp-001',
    title: 'Complete Q4 Sales Target',
    description: 'Achieve 120% of the Q4 sales target for the new product line.',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    status: 'In Progress',
    priority: 'Urgent',
    category: 'Sales Performance',
    smartCriteria: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
    milestones: [
      generateMilestone('goal-1', 'Secure 5 new enterprise clients', 'Identify and close deals with 5 new enterprise clients.', '2025-11-15', 'In Progress', 60),
      generateMilestone('goal-1', 'Train sales team on new product', 'Conduct 3 training sessions for the sales team.', '2025-10-30', 'Completed', 100),
      generateMilestone('goal-1', 'Exceed Q4 revenue by 20%', 'Achieve a 20% increase in revenue compared to Q3.', '2025-12-31', 'Not Started', 0),
    ],
    progressUpdates: [
      generateProgressUpdate('goal-1', 'Initial kickoff meeting held. Team is motivated.', 10),
      generateProgressUpdate('goal-1', 'Closed 2 enterprise deals. Training completed.', 45, 'milestone-2'),
    ],
    targetValue: 120,
    currentValue: 65,
    tags: ['sales', 'Q4', 'enterprise'],
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-10-25T14:30:00Z',
  },
  {
    id: 'goal-2',
    employeeId: 'emp-001',
    title: 'Develop New Feature X',
    description: 'Lead the development of Feature X from design to deployment.',
    startDate: '2025-09-15',
    endDate: '2025-11-30',
    status: 'In Progress',
    priority: 'High',
    category: 'Product Development',
    smartCriteria: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
    milestones: [
      generateMilestone('goal-2', 'Finalize design specifications', 'Complete all UI/UX and technical design documents.', '2025-09-30', 'Completed', 100),
      generateMilestone('goal-2', 'Implement backend API', 'Develop and test all necessary backend endpoints.', '2025-10-30', 'In Progress', 80),
      generateMilestone('goal-2', 'Build frontend UI', 'Create responsive user interface components.', '2025-11-15', 'In Progress', 40),
      generateMilestone('goal-2', 'Conduct user acceptance testing', 'Perform UAT with key stakeholders.', '2025-11-25', 'Not Started', 0),
    ],
    progressUpdates: [
      generateProgressUpdate('goal-2', 'Design phase completed ahead of schedule.', 20, 'milestone-1'),
      generateProgressUpdate('goal-2', 'Backend development is 80% complete. Starting frontend integration.', 60, 'milestone-2'),
    ],
    targetValue: 100,
    currentValue: 60,
    tags: ['development', 'feature', 'frontend', 'backend'],
    createdAt: '2025-09-10T09:00:00Z',
    updatedAt: '2025-10-28T11:00:00Z',
  },
  {
    id: 'goal-3',
    employeeId: 'emp-002',
    title: 'Complete Online Course on AI',
    description: 'Enroll and complete the Advanced AI Concepts online course.',
    startDate: '2025-08-01',
    endDate: '2025-12-31',
    status: 'On Hold',
    priority: 'Medium',
    category: 'Professional Development',
    smartCriteria: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
    milestones: [
      generateMilestone('goal-3', 'Complete Module 1-3', 'Finish the first three modules of the course.', '2025-09-30', 'Completed', 100),
      generateMilestone('goal-3', 'Complete Module 4-6', 'Finish modules four through six.', '2025-10-31', 'On Hold', 0),
    ],
    progressUpdates: [
      generateProgressUpdate('goal-3', 'Completed first 3 modules. Paused due to urgent project work.', 30),
    ],
    targetValue: 100,
    currentValue: 30,
    tags: ['learning', 'AI', 'course'],
    createdAt: '2025-07-25T13:00:00Z',
    updatedAt: '2025-10-10T16:00:00Z',
  },
  {
    id: 'goal-4',
    employeeId: 'emp-001',
    title: 'Improve Team Collaboration',
    description: 'Implement new tools and processes to enhance team collaboration and communication.',
    startDate: '2025-10-15',
    endDate: '2026-01-15',
    status: 'Not Started',
    priority: 'Low',
    category: 'Team Management',
    smartCriteria: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
    milestones: [
      generateMilestone('goal-4', 'Research collaboration tools', 'Evaluate 3 potential collaboration platforms.', '2025-10-30', 'Not Started', 0),
      generateMilestone('goal-4', 'Pilot selected tool', 'Run a pilot program with a small team.', '2025-11-30', 'Not Started', 0),
    ],
    progressUpdates: [],
    targetValue: null,
    currentValue: null,
    tags: ['team', 'collaboration', 'process'],
    createdAt: '2025-10-01T09:00:00Z',
    updatedAt: '2025-10-01T09:00:00Z',
  },
  {
    id: 'goal-5',
    employeeId: 'emp-003',
    title: 'Reduce Customer Churn by 10%',
    description: 'Implement strategies to decrease customer churn rate by 10% over the next quarter.',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    status: 'In Progress',
    priority: 'High',
    category: 'Customer Success',
    smartCriteria: { specific: true, measurable: true, achievable: true, relevant: true, timeBound: true },
    milestones: [
      generateMilestone('goal-5', 'Analyze churn data', 'Identify key reasons for customer churn.', '2025-10-15', 'Completed', 100),
      generateMilestone('goal-5', 'Develop retention strategies', 'Brainstorm and document 5 new retention strategies.', '2025-10-31', 'In Progress', 70),
      generateMilestone('goal-5', 'Implement top 2 strategies', 'Roll out the two most promising retention strategies.', '2025-11-30', 'Not Started', 0),
    ],
    progressUpdates: [
      generateProgressUpdate('goal-5', 'Initial data analysis complete. Key churn factors identified.', 25, 'milestone-1'),
      generateProgressUpdate('goal-5', 'Brainstorming session held, 3 strategies outlined.', 50, 'milestone-2'),
    ],
    targetValue: 10,
    currentValue: 5,
    tags: ['customer success', 'churn', 'retention'],
    createdAt: '2025-09-25T11:00:00Z',
    updatedAt: '2025-10-20T10:00:00Z',
  },
];
